### ISSUE TITLE
Translation of "Exercise"

### ISSUE THREAD

**Issue by Vouivre** [henningkerstan/exercisepoints#1]
Hi,

I'm testing your package and I would like to know if it's possible to translate the word "Exercise" in another language. I'm interested with french. 

Thank you!

**Comment by FelixBenning** [comment]
You could modify `\AtBeginExercise` cf. the [Manual](https://ftp.mpi-inf.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/macros/latex/contrib/exercisepoints/exercisepoints.pdf).

### Relevant Excerpt: 

For example, the minimal example style is implemented using the
following code.
```tex
\AtBeginExercise{%
     ~\smallskip\\\sffamily%
     \ifthenelse{\equal{\currentexercisetitle}{}}%
     {\textbf{Exercise~\currentexercisenumber}}%
     {%
     \textbf{Exercise~\currentexercisenumber:} %
     \currentexercisetitle%
     }%
     \,~\hfill\textbf{(\currentexercisepoints~Points)}%
     \smallskip\\\noindent\normalfont%
}
\AtEndExercise{~\smallskip\\}%
```

**Comment by henningkerstan** [comment]
Indeed, adjusting the exercise style is the solution. Thank you @FelixBenning.
